services:
  mini-simple-db-mysql:
    container_name: mini-simple-db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOTPASS}
      MYSQL_USER: Euclid
      MYSQL_PASSWORD: ${DBPASSWORD}
      MYSQL_DATABASE: simple_db
    ports:
      - "3306:3306"
    volumes:
      - "./db/simple_db.sql:/docker-entrypoint-initdb.d/1.sql"
    networks:
      - db_pythonrest_network
  api:
    build: ./API
    container_name: fastAPI
    environment: 
      DB_HOST: mini-simple-db
      DB_USER: Euclid
      DB_PASSWORD: ${DBPASSWORD}
      DB_NAME: simple_db
    ports: 
      - "3000:3000"
    depends_on:
      - mini-simple-db-mysql
    networks:
      - db_pythonrest_network
networks:
  db_pythonrest_network:
